import { EmptyState, ErrorState, LoadingState } from "../../../components/common/States";
import type { PredictionListResponse } from "../types";
import { PredictionConfidence } from "./PredictionConfidence";

const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const label = (value: string | null) => value ? value.charAt(0).toUpperCase() + value.slice(1) : "Not available";

export function PredictionPanel({ data, isPending, isError, onRetry }: { data?: PredictionListResponse; isPending: boolean; isError: boolean; onRetry: () => void }) {
  return <section aria-labelledby="prediction-heading" className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 id="prediction-heading" className="text-lg font-semibold">AI prediction</h2>{isPending ? <LoadingState label="Loading prediction" /> : isError ? <div className="mt-4"><ErrorState title="Unable to load prediction" message="Prediction evidence could not be loaded." onRetry={onRetry} /></div> : !data?.items.length ? <div className="mt-4"><EmptyState title="No prediction available" message="No prediction is available for this complaint yet." /></div> : (() => { const prediction = data.items[0]; return <div className="mt-5"><div className="flex items-center justify-between gap-4"><p className="text-sm text-slate-500">Latest of {data.count} prediction{data.count === 1 ? "" : "s"}</p><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${prediction.output_valid ? "bg-emerald-50 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200" : "bg-red-50 text-red-800 dark:bg-red-950 dark:text-red-200"}`}>{prediction.output_valid ? "Valid output" : "Invalid output"}</span></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Category</dt><dd className="mt-1 font-medium">{prediction.category?.name ?? "Not available"}</dd></div><div><dt className="text-slate-500">Department</dt><dd className="mt-1 font-medium">{prediction.department?.name ?? "Not available"}</dd></div><div><dt className="text-slate-500">Urgency</dt><dd className="mt-1 font-medium">{label(prediction.predicted_urgency)}</dd></div><div><dt className="text-slate-500">Confidence</dt><dd className="mt-1 font-medium"><PredictionConfidence value={prediction.confidence_score} /></dd></div><div><dt className="text-slate-500">Model</dt><dd className="mt-1 font-medium">{prediction.model_version.name} · {prediction.model_version.version}</dd></div><div><dt className="text-slate-500">Predicted</dt><dd className="mt-1 font-medium">{formatDate(prediction.created_at)}</dd></div></dl>{prediction.failure_code && <p className="mt-4 rounded-md bg-red-50 p-3 text-sm text-red-800 dark:bg-red-950 dark:text-red-200">Prediction failure: {prediction.failure_code}</p>}</div>; })()}</section>;
}
