import { ErrorState, LoadingState } from "../../../components/common/States";
import type { ReferenceListResponse, ReviewerComplaint } from "../types";

const urgencyLabel = (value: string | null) => value ? value.charAt(0).toUpperCase() + value.slice(1) : "Not finalized";

export function ReferenceDataSummary({ complaint, categories, departments, categoriesPending, departmentsPending, categoriesError, departmentsError, retryCategories, retryDepartments }: { complaint: ReviewerComplaint; categories?: ReferenceListResponse; departments?: ReferenceListResponse; categoriesPending: boolean; departmentsPending: boolean; categoriesError: boolean; departmentsError: boolean; retryCategories: () => void; retryDepartments: () => void }) {
  const category = categories?.items.find((item) => item.id === complaint.final_category_id);
  const department = departments?.items.find((item) => item.id === complaint.final_department_id);
  return <section aria-labelledby="routing-summary-heading" className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 id="routing-summary-heading" className="text-lg font-semibold">Final routing summary</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{categoriesPending ? <LoadingState label="Loading categories" /> : categoriesError ? <ErrorState title="Categories unavailable" message="Category reference data could not be loaded." onRetry={retryCategories} /> : <div><p className="text-sm text-slate-500">Category</p><p className="mt-1 font-medium">{complaint.final_category_id ? category?.name ?? "Reference unavailable" : "Not finalized"}</p></div>}{departmentsPending ? <LoadingState label="Loading departments" /> : departmentsError ? <ErrorState title="Departments unavailable" message="Department reference data could not be loaded." onRetry={retryDepartments} /> : <div><p className="text-sm text-slate-500">Department</p><p className="mt-1 font-medium">{complaint.final_department_id ? department?.name ?? "Reference unavailable" : "Not finalized"}</p></div>}</div><div className="mt-4 border-t border-slate-200 pt-4 dark:border-slate-800"><p className="text-sm text-slate-500">Urgency</p><p className="mt-1 font-medium">{urgencyLabel(complaint.final_urgency)}</p></div></section>;
}
