import { Link } from "react-router-dom";
import type { ReviewQueueItem } from "../types";
import { ReviewStatusBadge } from "./ReviewStatusBadge";

const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

export function ReviewQueueTable({ items }: { items: ReviewQueueItem[] }) {
  return <div className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200 dark:divide-slate-800"><thead className="bg-slate-50 dark:bg-slate-950"><tr><th scope="col" className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Complaint</th><th scope="col" className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Status</th><th scope="col" className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Created</th><th scope="col" className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Updated</th><th scope="col" className="px-4 py-3"><span className="sr-only">Action</span></th></tr></thead><tbody className="divide-y divide-slate-200 dark:divide-slate-800">{items.map((item) => <tr key={item.complaint_id} className="hover:bg-slate-50 dark:hover:bg-slate-800/50"><td className="px-4 py-4"><p className="font-medium">{item.title}</p><p className="mt-1 text-sm text-slate-500">{item.reference_number}</p></td><td className="whitespace-nowrap px-4 py-4"><ReviewStatusBadge status={item.current_status} /></td><td className="whitespace-nowrap px-4 py-4 text-sm text-slate-600 dark:text-slate-300">{formatDate(item.created_at)}</td><td className="whitespace-nowrap px-4 py-4 text-sm text-slate-600 dark:text-slate-300">{formatDate(item.updated_at)}</td><td className="whitespace-nowrap px-4 py-4 text-right"><Link to={`/review-queue/${item.complaint_id}`} className="inline-flex rounded-md border border-slate-300 px-3 py-2 text-sm font-semibold text-teal-700 hover:bg-slate-50 dark:border-slate-700 dark:text-teal-400 dark:hover:bg-slate-800">Open Review<span className="sr-only"> for {item.reference_number}</span></Link></td></tr>)}</tbody></table></div></div>;
}
