"""Stable public API dependency exports."""

from app.api.dependencies import (
    AccessToken,
    AuthServiceDependency,
    BenchmarkExperimentRepositoryDependency,
    BenchmarkPredictorFactoryDependency,
    BenchmarkResultRepositoryDependency,
    BenchmarkServiceDependency,
    ComplaintRepositoryDependency,
    ComplaintPredictorDependency,
    ComplaintServiceDependency,
    CurrentActiveUser,
    CurrentUser,
    DatabaseSession,
    DatasetVersionRepositoryDependency,
    ModelVersionRepositoryDependency,
    PredictionRepositoryDependency,
    PredictionServiceDependency,
    ReviewRepositoryDependency,
    ReviewServiceDependency,
    TransactionalAuthServiceDependency,
    TransactionalBenchmarkExperimentRepositoryDependency,
    TransactionalBenchmarkResultRepositoryDependency,
    TransactionalBenchmarkServiceDependency,
    TransactionalComplaintRepositoryDependency,
    TransactionalComplaintServiceDependency,
    TransactionalDatabaseSession,
    TransactionalDatasetVersionRepositoryDependency,
    TransactionalModelVersionRepositoryDependency,
    TransactionalPredictionRepositoryDependency,
    TransactionalPredictionServiceDependency,
    TransactionalReviewRepositoryDependency,
    TransactionalReviewServiceDependency,
    TransactionalUserRepositoryDependency,
    UserRepositoryDependency,
    get_auth_service,
    get_benchmark_experiment_repository,
    get_benchmark_predictor_factory,
    get_benchmark_result_repository,
    get_benchmark_service,
    get_complaint_repository,
    get_complaint_predictor,
    get_complaint_service,
    get_current_active_user,
    get_current_user,
    get_dataset_version_repository,
    get_prediction_repository,
    get_prediction_service,
    get_model_version_repository,
    get_review_repository,
    get_review_service,
    get_transactional_auth_service,
    get_transactional_benchmark_experiment_repository,
    get_transactional_benchmark_result_repository,
    get_transactional_benchmark_service,
    get_transactional_complaint_repository,
    get_transactional_complaint_service,
    get_transactional_dataset_version_repository,
    get_transactional_model_version_repository,
    get_transactional_prediction_repository,
    get_transactional_prediction_service,
    get_transactional_review_repository,
    get_transactional_review_service,
    get_transactional_user_repository,
    get_user_repository,
    oauth2_scheme,
)
from app.db.session import get_transactional_session
from app.api.routes import (
    auth_router,
    benchmarks_router,
    complaints_router,
    predictions_router,
    reviews_router,
)


_AUTHORIZATION_EXPORTS = {
    "AdministratorUser",
    "CustomerUser",
    "ReviewerOrAdministratorUser",
    "ReviewerUser",
}


def __getattr__(name: str):
    if name in _AUTHORIZATION_EXPORTS:
        from app import authz

        return getattr(authz, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

__all__ = [
    "AccessToken",
    "AuthServiceDependency",
    "BenchmarkExperimentRepositoryDependency",
    "BenchmarkPredictorFactoryDependency",
    "BenchmarkResultRepositoryDependency",
    "BenchmarkServiceDependency",
    "ComplaintRepositoryDependency",
    "ComplaintPredictorDependency",
    "ComplaintServiceDependency",
    "CurrentActiveUser",
    "CurrentUser",
    "DatabaseSession",
    "DatasetVersionRepositoryDependency",
    "ModelVersionRepositoryDependency",
    "PredictionRepositoryDependency",
    "PredictionServiceDependency",
    "ReviewRepositoryDependency",
    "ReviewServiceDependency",
    "TransactionalAuthServiceDependency",
    "TransactionalBenchmarkExperimentRepositoryDependency",
    "TransactionalBenchmarkResultRepositoryDependency",
    "TransactionalBenchmarkServiceDependency",
    "TransactionalComplaintRepositoryDependency",
    "TransactionalComplaintServiceDependency",
    "TransactionalDatabaseSession",
    "TransactionalDatasetVersionRepositoryDependency",
    "TransactionalModelVersionRepositoryDependency",
    "TransactionalPredictionRepositoryDependency",
    "TransactionalPredictionServiceDependency",
    "TransactionalReviewRepositoryDependency",
    "TransactionalReviewServiceDependency",
    "TransactionalUserRepositoryDependency",
    "UserRepositoryDependency",
    "get_auth_service",
    "get_benchmark_experiment_repository",
    "get_benchmark_predictor_factory",
    "get_benchmark_result_repository",
    "get_benchmark_service",
    "get_complaint_repository",
    "get_complaint_predictor",
    "get_complaint_service",
    "get_current_active_user",
    "get_current_user",
    "get_dataset_version_repository",
    "get_prediction_repository",
    "get_prediction_service",
    "get_model_version_repository",
    "get_review_repository",
    "get_review_service",
    "get_transactional_auth_service",
    "get_transactional_benchmark_experiment_repository",
    "get_transactional_benchmark_result_repository",
    "get_transactional_benchmark_service",
    "get_transactional_complaint_repository",
    "get_transactional_complaint_service",
    "get_transactional_dataset_version_repository",
    "get_transactional_model_version_repository",
    "get_transactional_prediction_repository",
    "get_transactional_prediction_service",
    "get_transactional_review_repository",
    "get_transactional_review_service",
    "get_transactional_session",
    "get_transactional_user_repository",
    "get_user_repository",
    "oauth2_scheme",
    "auth_router",
    "benchmarks_router",
    "complaints_router",
    "predictions_router",
    "reviews_router",
    "AdministratorUser",
    "CustomerUser",
    "ReviewerOrAdministratorUser",
    "ReviewerUser",
]
