import { ComplaintStatusBadge } from "./ComplaintStatusBadge";
import type { Complaint } from "../types";

const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "long", timeStyle: "short" }).format(new Date(value));
const labelUrgency = (value: string) => value.charAt(0).toUpperCase() + value.slice(1);

export function ComplaintDetails({ complaint }: { complaint: Complaint }) {
  return <div className="space-y-6"><section className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-slate-500">{complaint.reference_number}</p><h2 className="mt-1 text-2xl font-semibold">{complaint.title}</h2></div><ComplaintStatusBadge status={complaint.current_status} /></div><dl className="mt-6 grid gap-5 border-t border-slate-200 pt-5 text-sm dark:border-slate-800 sm:grid-cols-2"><div><dt className="text-slate-500">Created</dt><dd className="mt-1 font-medium">{formatDate(complaint.created_at)}</dd></div><div><dt className="text-slate-500">Last updated</dt><dd className="mt-1 font-medium">{formatDate(complaint.updated_at)}</dd></div></dl></section><section className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 className="font-semibold">Complaint description</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-700 dark:text-slate-300">{complaint.description}</p></section><section className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 className="font-semibold">Routing outcome</h3>{complaint.final_urgency ? <dl className="mt-4"><dt className="text-sm text-slate-500">Final urgency</dt><dd className="mt-1 font-medium">{labelUrgency(complaint.final_urgency)}</dd></dl> : <p className="mt-2 text-sm text-slate-600 dark:text-slate-400">A final routing outcome is not available yet.</p>}</section></div>;
}
