import { Link } from "react-router-dom";
import { ComplaintStatusBadge } from "./ComplaintStatusBadge";
import type { Complaint } from "../types";

const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

export function ComplaintTable({ complaints }: { complaints: Complaint[] }) {
  return <div className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200 dark:divide-slate-800"><thead className="bg-slate-50 dark:bg-slate-950"><tr><th scope="col" className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Complaint</th><th scope="col" className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Status</th><th scope="col" className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Created</th><th scope="col" className="px-4 py-3"><span className="sr-only">Open</span></th></tr></thead><tbody className="divide-y divide-slate-200 dark:divide-slate-800">{complaints.map((complaint) => <tr key={complaint.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/50"><td className="max-w-md px-4 py-4"><p className="font-medium">{complaint.title}</p><p className="mt-1 truncate text-sm text-slate-500">{complaint.reference_number} · {complaint.description}</p></td><td className="whitespace-nowrap px-4 py-4"><ComplaintStatusBadge status={complaint.current_status} /></td><td className="whitespace-nowrap px-4 py-4 text-sm text-slate-600 dark:text-slate-300">{formatDate(complaint.created_at)}</td><td className="whitespace-nowrap px-4 py-4 text-right"><Link className="text-sm font-semibold text-teal-700 hover:underline dark:text-teal-400" to={`/complaints/${complaint.id}`}>View details<span className="sr-only"> for {complaint.title}</span></Link></td></tr>)}</tbody></table></div></div>;
}
